### ISSUE TITLE
cant launch mag calibration

### ISSUE THREAD

**Issue by uwu12234** [SBG-Systems/sbg_ros2_driver#6]
Hi,

I am unable to launch the mag calibration.
This is the reply from ros

[INFO] [launch]: All log files can be found below /home/nav2/.ros/log/2022-06-10-16-24-14-394591-nav2-desktop-569205
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [sbg_device_mag-1]: process started with pid [569211]
[ERROR] [sbg_device_mag-1]: process has died [pid 569211, exit code -11, cmd '/home/nav2/nav2_ws/install/sbg_driver/lib/sbg_driver/sbg_device_mag --ros-args --params-file /home/nav2/nav2_ws/install/sbg_driver/share/sbg_driver/config/example/ellipse_E_default.yaml'].

Truly appreciate any help thanks.

**Comment by uwu12234** [comment]
Never mind, it is solved.

#include "sbg_device.h"

using sbg::SbgDevice;

int main(int argc, char **argv)
{
  printf("test123");
  rclcpp::init(argc, argv);
  //rclcpp::Node::SharedPtr node_handle;
  rclcpp::Node node_handle("sbg_device");
   
  try
  {
    uint32_t loopFrequency;
  
    RCLCPP_INFO(node_handle.get_logger(), "SBG DRIVER - Init node, load params and connect to the device");
    SbgDevice sbg_device(node_handle);
    
    RCLCPP_INFO(node_handle.get_logger(), "SBG DRIVER - Initialize device for receiving data");
    sbg_device.initDeviceForMagCalibration();
    sbg_device.initDeviceForReceivingData();
    
    loopFrequency = sbg_device.getUpdateFrequency();
    RCLCPP_INFO(node_handle.get_logger(), "SBG DRIVER - ROS Node frequency : %u Hz", loopFrequency);
    rclcpp::Rate loop_rate(loopFrequency);

    while (rclcpp::ok())
    {
      sbg_device.periodicHandle();
      loop_rate.sleep();
    }
    
    //rclcpp::spin(node_handle);
		
    return 0;
  }
  
  catch (std::exception const& refE)
  {
   RCLCPP_ERROR(node_handle.get_logger(), "SBG_DRIVER - [MagNode] Error - %s.", refE.what());
  }


  return 0;
}

**Comment by uwu12234** [comment]
Never mind, it is solved.
#include "sbg_device.h"

using sbg::SbgDevice;

int main(int argc, char **argv)
{
  printf("test123");
  rclcpp::init(argc, argv);
  //rclcpp::Node::SharedPtr node_handle;
  rclcpp::Node node_handle("sbg_device");
   
  try
  {
    uint32_t loopFrequency;
  
    RCLCPP_INFO(node_handle.get_logger(), "SBG DRIVER - Init node, load params and connect to the device");
    SbgDevice sbg_device(node_handle);
    
    RCLCPP_INFO(node_handle.get_logger(), "SBG DRIVER - Initialize device for receiving data");
    sbg_device.initDeviceForMagCalibration();
    sbg_device.initDeviceForReceivingData();
    
    loopFrequency = sbg_device.getUpdateFrequency();
    RCLCPP_INFO(node_handle.get_logger(), "SBG DRIVER - ROS Node frequency : %u Hz", loopFrequency);
    rclcpp::Rate loop_rate(loopFrequency);

    while (rclcpp::ok())
    {
      sbg_device.periodicHandle();
      loop_rate.sleep();
    }
    
    //rclcpp::spin(node_handle);
		
    return 0;
  }
  
  catch (std::exception const& refE)
  {
   RCLCPP_ERROR(node_handle.get_logger(), "SBG_DRIVER - [MagNode] Error - %s.", refE.what());
  }


  return 0;
}

**Comment by RobinBaruffa** [comment]
Why isn't this pushed in the main repo ?? 
This problem is not solved if one needs to search in the issues and copy and paste stuff from someone to make it work

**Comment by saitama-00** [comment]
can you explain where should i use this code to get this working?
